apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maypp
    version: v1
  name: myapp-v1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
      - image: docker.io/library/nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "100m"   # 반드시 설정 필요
          limits:
            cpu: "500m"               
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      #serviceAccount: mynginx
      #serviceAccountName: mynginx
      terminationGracePeriodSeconds: 30
