apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: helloworld
    version: v1
  name: hpa-helloworld-v1
  namespace: gitops-nginx
spec:
  maxReplicas: 20
  metrics:
    - resource:
        name: cpu
        target:
          averageValue: '60'
          type: AverageValue
      type: Resource
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld-v1
