apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mynginx
spec:
  ingressClassName: alb
  rules:
  - host: nginx.kubesphere.kr
    http:
      paths:
      - backend:
          serviceName: helloworld
          servicePort: 80
        path: /hello
        pathType: Prefix
      - backend:
          serviceName: myapp-1
          servicePort: 80
        path: /
        pathType: Prefix
