apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mynginx
spec:
  ingressClassName: alb
  rules:
  - host: nginx.kubesphere.kr
    http:
      paths:
      - backend:
          service:
            name: helloworld
            port:
              name: http
        path: /hello
        pathType: Prefix
      - backend:
          service:
            name: myapp-1
            port:
              name: http
        path: /
        pathType: Prefix
