apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: myapp
    version: v1
  name: myapp-v1
spec:
  maxReplicaCount: 20
  minReplicaCount: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-v1
  triggers:
    - metadata:
        value: '60'
      metricType: AverageValue
      name: T_60__cpu
      type: cpu
